### ISSUE TITLE
Variable access doesn't need to be wrapped in strings

### ISSUE THREAD

**Issue by kitsunet** [jeremieroulin/fluid-converter#3]
According to the example on the website an `argument="{foo.bar}"` is converted to `argument: '{foo.bar}'` but that could be simplified to `argument: foo.bar`. If it's possible to detect that this is a variable access, the second syntax would be preferred.

**Comment by jeremieroulin** [comment]
Hi, I have a question about that. If we have `<f:if condition="{obj.prop} == {anotherObj.prop}"><f:then>condition is met</f:then><f:else>condition is not met</f:else></f:if>`, should the inline notation be like `{f:if (condition: obj.prop == anotherObj.prop, then: 'condition is met', else: 'condition is not met '}` or like `{f:if (condition: obj.prop == {anotherObj.prop}, then: 'condition is met', else: 'condition is not met '}`?
Thank you.

**Comment by kitsunet** [comment]
Right, that's the tricky part, because in that case it must be a string as far as I know. `condition: '{obj.prop} == {anotherObj.prop}'`
